### PR TITLE
fix #13

### LINKED ISSUE #13: Error when logging after first install since shiori 1.5.3
Installing version 1.5.3 on a system where not previous version of shiori was installed will get the following error:
"failed to fetch accounts: SQL logic error: no such table: account (1) (500)"
When trying to log in with the default shiori/gopher credential.

As per this issue https://github.com/go-shiori/shiori/issues/447, a shiori migrate command is necessary after installing to fix this.
Such command shall be added to the yunohost install scripts with 1.5.3.

One way to workaround this while this is fixed is to install the previous version. This can be done with the following command:
yunohost app install https://github.com/YunoHost-Apps/shiori_ynh/tree/4062f49dfe9e87dfe4818958634addd834ebfc1d

This will also workaround the CSS issue : https://github.com/YunoHost-Apps/shiori_ynh/issues/12 as this issue will prevent you to create a new account even if you solve the migration command needed as you won't have the "config" button in the menu bar to create a new account.

### PR DESCRIPTION
**Pull request by navanchauhan**
runs migrate command on a fresh install

### CODE REVIEW

**Comment by navanchauhan** [comment]
Migration while passing the Shiori data dir env does not work for some reason, this PR updates the install script to run the migration while passing the `--portable` flag and then moves the sqlite database to the correct location.

**Comment by navanchauhan** [comment]
!testme

**Comment by navanchauhan** [comment]
!tesme

**Comment by navanchauhan** [comment]
!testme

**Comment by navanchauhan** [comment]
@ericgaspar have a look when you have time

this fixes #13

**Comment by ericgaspar** [comment]
Thanks again for the work!
(I will push to master when #12 is fixed upstream)

**Pull request merged**
