### PR TITLE
Testing

### LINKED ISSUE #13: Error when logging after first install since shiori 1.5.3
Installing version 1.5.3 on a system where not previous version of shiori was installed will get the following error:
"failed to fetch accounts: SQL logic error: no such table: account (1) (500)"
When trying to log in with the default shiori/gopher credential.

As per this issue https://github.com/go-shiori/shiori/issues/447, a shiori migrate command is necessary after installing to fix this.
Such command shall be added to the yunohost install scripts with 1.5.3.

One way to workaround this while this is fixed is to install the previous version. This can be done with the following command:
yunohost app install https://github.com/YunoHost-Apps/shiori_ynh/tree/4062f49dfe9e87dfe4818958634addd834ebfc1d

This will also workaround the CSS issue : https://github.com/YunoHost-Apps/shiori_ynh/issues/12 as this issue will prevent you to create a new account even if you solve the migration command needed as you won't have the "config" button in the menu bar to create a new account.

### PR DESCRIPTION
**Pull request by ericgaspar**
- Fix #13

### CODE REVIEW

**Comment by ericgaspar** [comment]
!testme

**Comment by sphinxc0re** [comment]
This doesn't seem to fix it. I'm still getting the error after the upgrade.

**Comment by AIndoria** [comment]
> This doesn't seem to fix it. I'm still getting the error after the upgrade.

I can confirm that this is still an issue. Wasn't the migrate command supposed to run automagically after this? I still have to manually run it.

**Comment by ericgaspar** [comment]
please open an issue with logs please.

**Pull request merged**
